### ISSUE TITLE
Migrate all `docker-compose` commands to `docker compose` commands

### ISSUE THREAD

**Issue by navarr** [wardenenv/warden#625]
Will resolve #527, #622

**Comment by sprankhub** [comment]
Since quite some users seem to bump into this, I think this should have high priority :see_no_evil: Also, according to https://docs.docker.com/compose/compose-v2/#differences-between-compose-v1-and-compose-v2, it could be as easy as replacing `docker-compose` to `docker compose` without any additional changes:

> The `compose` command in the Docker CLI supports most of the `docker-compose` commands and flags. It is expected to be a drop-in replacement for `docker-compose`.

Do you see any specific things to watch out for, @navarr? If not and you do not get to it, I'd consider sending a PR.

**Comment by navarr** [comment]
@sprankhub I thought there were.  I previously did this in Den but I only see the one commit, so I've ported that over in #631 

If you have the capability to test this particular issue, I'd appreciate some additional eyes on it.

**Comment by sprankhub** [comment]
@navarr, sorry for the late feedback. I've installed the `docker-compose-plugin` branch from the PR to `/opt/warden` and ran `/opt/warden/bin/warden env pull && /opt/warden/bin/warden env up --force-recreate`. From the fancier output, I can tell that indeed, docker compose v2 is used. The project still seems to run fine, so I think we are good. Could you merge and release a new version soonish? Looks like there were quite some people affected by this. Thanks!

**Comment by navarr** [comment]
@sprankhub unfortunately that's docker compose v1 vs v2. I can do some research to see if we're stuck with it or not but so far I've always presumed so

**Comment by sprankhub** [comment]
Thanks for the info, @navarr. Given that it is a one-time change, I'm fine with it. More important to make the switch to docker compose v2 :)
