### ISSUE TITLE
[Image] PHP FPM 7.2 not working in Apple Silicon Chip

### ISSUE THREAD

**Issue by MagePsycho** [wardenenv/warden#755]
### Version of Warden

0.14.2

### Operating System and Installation Method

Mac OS 14.3.1 (M3 Chip) via Brew

### Image

 php-fpm 7.2

### Describe the Bug

Using PHP 7.2, gives an error:

> php-fpm The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### To Reproduce

1. In .env use `PHP_VERSION=7.2`
2. `warden env up`
You will see the mentioned error.

### Expected Behavior

M3 chip should also support PHP 7.2 image

**Comment by bap14** [comment]
@MagePsycho This may not be possible because PHP 7.2 is so old, some of the required packages may not be available in the arm64 variant images. There is nothing preventing the amd64 variant from running an arm (M1, M2, M3) chip, it's just that it won't be as performant as it could be.

This is not an error, this is just a warning. You also get this any time you start a project with Elasticsearch on an arm64 processor.
